#!/usr/bin/perl
use strict;
use warnings;

sub main {
    open( my $fh, '>', '/tmp/to_write.txt' ) or die "Couldn't open file file.txt, $!";
    print $fh "My first report generated by perl\n";

    my @list = ( 'a', 'list', 'of', 'lines' );

    foreach my $line (@list) {
        print $fh "$line\n";
    }

    close($fh) || die "Couldn't close file properly";
}

main();
